package proxy

// The generated half of the squid config: per-VM access rules.
//
// host/squid.conf.in stays a static, reviewable template; what varies with
// the set of sandboxes is generated here and pushed as its own file,
// /etc/squid/vm_access.conf, pulled in by an `include` that sits between the
// template's to_internal deny and its base-port allow. The split is what
// keeps VM churn on the `squid -k reconfigure` path - the config file proper
// never changes when a sandbox comes or goes, and only a template change pays
// the restart that severs live tunnels.
//
// The ordering INSIDE the generated file is a security property, asserted by
// the invariants test: each VM gets an allow on its port against its list,
// then a deny on that port. The deny is a hard cap - whatever rules follow,
// below it or in a future template, a VM's egress is decided by its own list
// and nothing else.

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"time"

	"github.com/PtrMzk/ptrbox/internal/config"
)

// Paths inside the proxy VM for the per-VM machinery.
const (
	VMAccessPath   = "/etc/squid/vm_access.conf"
	vmAllowlistDir = "/etc/squid/allowed.d"
)

// vmAllowlistVMPath is where one VM's allowlist lands inside the proxy VM.
func vmAllowlistVMPath(name string) string {
	return vmAllowlistDir + "/" + name + ".txt"
}

// VMAccessConf renders the per-VM access rules for a set of allocations.
// Exported for the invariants test, which asserts the shape of these rules
// the way it asserts the template's: generated config is config.
func VMAccessConf(ports map[string]int) string {
	names := make([]string, 0, len(ports))
	for name := range ports {
		names = append(names, name)
	}
	sort.Strings(names)

	out := "# Generated by ptrbox - per-VM access rules. Do not edit: the next sync\n" +
		"# rewrites this file from the port allocations and the per-VM allowlists\n" +
		"# under ~/.config/ptrbox/allowed_domains.d/ on the host.\n"
	for _, name := range names {
		port := ports[name]
		out += fmt.Sprintf(
			"acl vm_%[1]s_port localport %[2]d\n"+
				"acl vm_%[1]s_domains dstdomain \"%[3]s\"\n"+
				"http_access allow from_forward CONNECT vm_%[1]s_port vm_%[1]s_domains\n"+
				"http_access deny vm_%[1]s_port\n",
			name, port, vmAllowlistVMPath(name))
	}
	return out
}

// EnsureVMAllowlist seeds a VM's allowlist from the template when it is
// absent, and returns its contents either way. `ptrbox allow` goes through
// this so the first touch of a VM's list starts from the template - a file
// holding one hand-added domain and nothing else would boot a sandbox that
// can reach it and nothing else, including Anthropic.
func (p *Proxy) EnsureVMAllowlist(name string) (string, error) {
	template, err := os.ReadFile(config.AllowlistPath())
	if err != nil {
		return "", fmt.Errorf("no allowlist at %s - run 'ptrbox install' first", config.AllowlistPath())
	}

	seed, err := p.vmSeed(name, template)
	if err != nil {
		return "", err
	}
	return p.ensureVMAllowlist(name, seed)
}

// vmSeed renders the template into the list one VM starts from.
//
// The runtimes are THIS VM's, not the host's defaults: `ptrbox allow <vm>`
// before the VM exists must seed the same bytes `ptrbox new` would, and that
// answer lives in that VM's own config file. A per-VM file that does not parse
// fails here rather than quietly seeding a list built from someone else's
// settings.
func (p *Proxy) vmSeed(name string, template []byte) ([]byte, error) {
	cfg, err := p.Cfg.Overlay(name)
	if err != nil {
		return nil, fmt.Errorf("seeding the allowlist for %q: %w", name, err)
	}
	seed, err := SeedFor(template, cfg)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", config.AllowlistPath(), err)
	}
	return seed, nil
}

// Group markers in the template. Everything outside a group is copied
// unchanged; a group survives if the VM has ANY of the runtimes named on its
// marker, which is what lets a tool driven from either runtime (Playwright)
// say so in one line.
const (
	requiresMarker = "@requires"
	endMarker      = "@end"
)

// SeedFor renders the template into the list one VM starts from: the groups
// whose runtimes that VM does not have are replaced by a line saying they were
// left out, and the markers themselves do not survive - a VM's list is a plain
// list, and nothing re-reads it against the config later. Exported for the
// invariants test, which reads the seeded result rather than the template.
//
// A marker naming something that is not a runtime is an ERROR, not a group
// silently kept or silently dropped: the template is a file people edit, and
// both quiet answers are wrong in a way nobody would notice - one grants
// domains nothing can use, the other takes away domains somebody asked for.
func SeedFor(template []byte, cfg *config.Config) ([]byte, error) {
	var out bytes.Buffer
	scanner := bufio.NewScanner(bytes.NewReader(template))
	group, keep := "", true

	for line := 1; scanner.Scan(); line++ {
		text := scanner.Text()
		directive, argument := parseMarker(text)
		switch directive {
		case requiresMarker:
			if group != "" {
				return nil, fmt.Errorf("line %d: %s inside the %q group - groups do not nest",
					line, requiresMarker, group)
			}
			runtimes := strings.Fields(argument)
			if len(runtimes) == 0 {
				return nil, fmt.Errorf("line %d: %s names no runtime (expected one of: %s)",
					line, requiresMarker, strings.Join(config.Toolchains, " "))
			}
			for _, runtime := range runtimes {
				if !slices.Contains(config.Toolchains, runtime) {
					return nil, fmt.Errorf("line %d: %q is not a runtime (expected one of: %s)",
						line, runtime, strings.Join(config.Toolchains, " "))
				}
			}
			group, keep = argument, slices.ContainsFunc(runtimes, cfg.Wants)
			if !keep {
				fmt.Fprintf(&out, "# (omitted: this VM has no %s)\n", strings.Join(runtimes, " or "))
			}
		case endMarker:
			if group == "" {
				return nil, fmt.Errorf("line %d: %s with no %s above it", line, endMarker, requiresMarker)
			}
			group, keep = "", true
		case "":
		default:
			// A directive nobody implements, which in practice is one of the
			// two above misspelled - and a misspelled @requires is a group
			// that silently applies to everyone, which is the failure this
			// whole filter exists to remove.
			return nil, fmt.Errorf("line %d: unknown directive %s (expected %s or %s)",
				line, directive, requiresMarker, endMarker)
		}
		// Markers do not survive into a VM's list: nothing re-reads that file
		// against the config, so a marker in it would claim a relationship
		// that no longer exists.
		if directive == "" && keep {
			out.WriteString(text)
			out.WriteByte('\n')
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, err
	}
	if group != "" {
		return nil, fmt.Errorf("the %q group is never closed with %s", group, endMarker)
	}
	return out.Bytes(), nil
}

// parseMarker reads a `# @directive args` comment. Anything else - a domain, a
// blank line, an ordinary comment - comes back with an empty directive and is
// copied verbatim.
func parseMarker(line string) (directive, argument string) {
	text := strings.TrimSpace(line)
	if !strings.HasPrefix(text, "#") {
		return "", ""
	}
	text = strings.TrimSpace(strings.TrimPrefix(text, "#"))
	if !strings.HasPrefix(text, "@") {
		return "", ""
	}
	directive, argument, _ = strings.Cut(text, " ")
	return directive, strings.TrimSpace(argument)
}

// ensureVMAllowlist returns a VM's host-side allowlist, writing seed there
// when it is absent. Seeding here rather than only in `new` is what makes a
// deleted file a RESET instead of a parse error: the generated rules reference
// the file, so a mapped VM without one would stop squid, which is every
// sandbox's network. Create what is absent, never touch what is present -
// which is also why the runtime filter cannot reach an existing file: from the
// moment it is written it is the user's, and turning a runtime off later
// changes what the next VM starts from, not what this one may reach.
func (p *Proxy) ensureVMAllowlist(name string, seed []byte) (string, error) {
	path := config.VMAllowlistPath(name)
	if body, err := os.ReadFile(path); err == nil {
		return string(body), nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}

	body := fmt.Sprintf("# Egress allowlist for VM %q, seeded from allowed_domains.txt on %s.\n"+
		"# This file alone decides what this VM may CONNECT to - edit it with\n"+
		"# `ptrbox allow %s`, or delete it to re-seed from the template.\n\n",
		name, time.Now().Format("2006-01-02"), name) + string(seed)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	p.Out.Say("seeded %s from the template", path)
	if err := config.RecordManifest("wrote " + path); err != nil {
		return "", err
	}
	return body, nil
}
