package proxy

// The generated half of the squid config: per-VM access rules.
//
// host/squid.conf.in stays a static, reviewable template; what varies with
// the set of sandboxes is generated here and pushed as its own file,
// /etc/squid/vm_access.conf, pulled in by an `include` that sits between the
// template's to_internal deny and its base-port allow. The split is what
// keeps VM churn on the `squid -k reconfigure` path - the config file proper
// never changes when a sandbox comes or goes, and only a template change pays
// the restart that severs live tunnels.
//
// The ordering INSIDE the generated file is a security property, asserted by
// the invariants test: each VM gets an allow on its port against its list,
// then a deny on that port. The deny is a hard cap - whatever rules follow,
// below it or in a future template, a VM's egress is decided by its own list
// and nothing else.

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/PtrMzk/ptrbox/internal/config"
)

// Paths inside the proxy VM for the per-VM machinery.
const (
	VMAccessPath   = "/etc/squid/vm_access.conf"
	vmAllowlistDir = "/etc/squid/allowed.d"
)

// vmAllowlistVMPath is where one VM's allowlist lands inside the proxy VM.
func vmAllowlistVMPath(name string) string {
	return vmAllowlistDir + "/" + name + ".txt"
}

// VMAccessConf renders the per-VM access rules for a set of allocations.
// Exported for the invariants test, which asserts the shape of these rules
// the way it asserts the template's: generated config is config.
func VMAccessConf(ports map[string]int) string {
	names := make([]string, 0, len(ports))
	for name := range ports {
		names = append(names, name)
	}
	sort.Strings(names)

	out := "# Generated by ptrbox - per-VM access rules. Do not edit: the next sync\n" +
		"# rewrites this file from the port allocations and the per-VM allowlists\n" +
		"# under ~/.config/ptrbox/allowed_domains.d/ on the host.\n"
	for _, name := range names {
		port := ports[name]
		out += fmt.Sprintf(
			"acl vm_%[1]s_port localport %[2]d\n"+
				"acl vm_%[1]s_domains dstdomain \"%[3]s\"\n"+
				"http_access allow from_forward CONNECT vm_%[1]s_port vm_%[1]s_domains\n"+
				"http_access deny vm_%[1]s_port\n",
			name, port, vmAllowlistVMPath(name))
	}
	return out
}

// ensureVMAllowlist returns a VM's host-side allowlist, seeding it from the
// template when it is absent. Seeding here rather than only in `new` is what
// makes a deleted file a RESET instead of a parse error: the generated rules
// reference the file, so a mapped VM without one would stop squid, which is
// every sandbox's network. Create what is absent, never touch what is
// present.
func (p *Proxy) ensureVMAllowlist(name string, template []byte) (string, error) {
	path := config.VMAllowlistPath(name)
	if body, err := os.ReadFile(path); err == nil {
		return string(body), nil
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", err
	}

	body := fmt.Sprintf("# Egress allowlist for VM %q, seeded from allowed_domains.txt on %s.\n"+
		"# This file alone decides what this VM may CONNECT to - edit it with\n"+
		"# `ptrbox allow %s`, or delete it to re-seed from the template.\n\n",
		name, time.Now().Format("2006-01-02"), name) + string(template)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		return "", err
	}
	p.Out.Say("seeded %s from the template", path)
	if err := config.RecordManifest("wrote " + path); err != nil {
		return "", err
	}
	return body, nil
}
